version: '3.5'

services:
  backend:
      build: ./backend
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
  frontend:
      build: ./frontend
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
